# Generated by Django 5.0.6 on 2024-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicalproperty',
            options={'verbose_name': 'Chemical Property', 'verbose_name_plural': 'Chemical Properties'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='cropacceptabelvalues',
            options={'verbose_name': 'Crop Acceptable Value', 'verbose_name_plural': 'Crop Acceptable Values'},
        ),
    ]
