# Generated by Django 5.0.6 on 2024-06-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_chemicalproperty_options_alter_crop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_dose', models.FloatField()),
                ('max_dose', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.chemicalproperty')),
            ],
            options={
                'verbose_name': 'Fertilizer',
                'verbose_name_plural': 'Fertilizers',
            },
        ),
    ]
