# Generated by Django 5.0.6 on 2024-10-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crop Group',
                'verbose_name_plural': 'Crop Groups',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.cropgroup'),
        ),
        migrations.CreateModel(
            name='CropGroupFertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.cropgroup')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.fertilizer')),
            ],
            options={
                'verbose_name': 'Crop Group Fertilizer',
                'verbose_name_plural': 'Crop Group Fertilizers',
            },
        ),
    ]
