# Generated by Django 5.0.6 on 2024-10-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_cropgroup_crop_crop_group_cropgroupfertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerMixedFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_dose', models.FloatField()),
                ('max_dose', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.chemicalproperty')),
                ('crop_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.cropgroup')),
            ],
            options={
                'verbose_name': 'FertilizerMixedFirst',
                'verbose_name_plural': 'FertilizerMixedFirst',
            },
        ),
        migrations.CreateModel(
            name='FertilizerMixedSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_dose', models.FloatField()),
                ('max_dose', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.chemicalproperty')),
                ('crop_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.cropgroup')),
            ],
            options={
                'verbose_name': 'FertilizerMixedSecond',
                'verbose_name_plural': 'FertilizerMixedSecond',
            },
        ),
    ]
