# Generated by Django 5.0.6 on 2024-10-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_fertilizermixedfirst_fertilizermixedsecond'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='crop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.cropgroup'),
        ),
        migrations.DeleteModel(
            name='CropGroupFertilizer',
        ),
    ]
