# Generated by Django 5.0.6 on 2024-12-24 04:10

import crops.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0006_fertilizer_crop_group_delete_cropgroupfertilizer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sample_type",
                    models.CharField(
                        choices=[("soil", "Soil"), ("plant", "Plant")], max_length=5
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[("soil", "Soil"), ("plant", "Plant")], max_length=5
                    ),
                ),
                ("lab_type", models.CharField(max_length=100)),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_input",
                    models.FileField(
                        upload_to=crops.models.InputSample.get_upload_path
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
        ),
    ]
