# Generated by Django 5.0.6 on 2024-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0007_labtype_inputsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputsample",
            name="is_processed_successfully",
            field=models.BooleanField(default=False),
        ),
    ]
