# Generated by Django 5.0.6 on 2025-01-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0008_inputsample_is_processed_successfully"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="analysis_type",
            field=models.CharField(
                blank=True,
                choices=[("soil", "Soil"), ("plant", "Plant")],
                max_length=100,
                null=True,
            ),
        ),
    ]
