from django.db import models
from uuid import uuid4

# python manage.py makemigrations analysis_submissions
# python manage.py migrate

ANALYSIS_TYPE_CHOICES = [
    ('soil', 'Soil'),                   # Soil analysis by user, can be used by agronomists for soil analysis
    ('plant', 'Plant'),                 # Plant analysis by user, can be used by agronomists for plant analysis,
    ('plant_report', 'Plant Report'),   # Plant report generated by agronomist, only agronomists can generate this report
]

PLATFORMS_ROLES = [
    ('user', 'User'),
    ('agronomist', 'Agronomist'),
]

def randomUUID():
    id = uuid4()
    id_str = id.hex
    return id_str[0:16]

# Create your models here.
class ReportSubmission(models.Model):
    """
    Model to store report submission data.
    """
    # User information, we have them stored in a cookie and will save them in the database when the user submits a report
    user_id = models.IntegerField(blank=False, null=False)  # user_id is an integer, should never be blank or null
    user_email = models.EmailField(max_length=255)          # user_email is a string, should never be blank or null
    user_role = models.CharField(max_length=50, choices=PLATFORMS_ROLES, default='user')  # user_role is a string, should never be blank or null
    
    # A unique identifier for the report submitted by the user, randomly generated
    report_id = models.CharField(max_length=255, unique=True, default=randomUUID)

    # Report details
    analysis_type = models.CharField(max_length=100, choices=ANALYSIS_TYPE_CHOICES, blank=True, null=True)
    report_data = models.JSONField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  

    def __str__(self):
        return f"ReportSubmission(report_id={self.report_id}, user_id={self.user_id}, analysis_type={self.analysis_type})"

    class Meta:
        verbose_name = "Report Submission"
        verbose_name_plural = "Report Submissions"