# Generated by Django 4.2.19 on 2025-05-26 16:48

import analysis_submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=255)),
                ('user_role', models.CharField(choices=[('user', 'User'), ('agronomist', 'Agronomist')], default='user', max_length=50)),
                ('report_id', models.CharField(default=analysis_submissions.models.randomUUID, max_length=255, unique=True)),
                ('analysis_type', models.CharField(blank=True, choices=[('soil', 'Soil'), ('plant', 'Plant')], max_length=100, null=True)),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Submission',
                'verbose_name_plural': 'Report Submissions',
            },
        ),
    ]
