# Generated by Django 4.2.19 on 2025-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('soil', 'Soil'), ('plant', 'Plant'), ('plant_report', 'Plant Report')], max_length=100, null=True),
        ),
    ]
