# Generated by Django 5.0.6 on 2025-01-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0008_inputsample_is_processed_successfully"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_group", models.CharField(max_length=100)),
                ("lab_type", models.CharField(max_length=100)),
                ("file_input", models.FileField(upload_to="soil_samples/")),
            ],
        ),
        migrations.CreateModel(
            name="BaseSaturationAcceptableValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_value", models.FloatField()),
                ("upper_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.chemicalproperty",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Saturation Acceptable Value",
                "verbose_name_plural": "Base Saturation Acceptable Values",
            },
        ),
        migrations.CreateModel(
            name="SoilAcceptableValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_value", models.FloatField()),
                ("upper_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.chemicalproperty",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Acceptable Value",
                "verbose_name_plural": "Soil Acceptable Values",
            },
        ),
    ]
