# Generated by Django 5.0.6 on 2025-02-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0009_crop_analysis_type"),
        ("soil_analysis", "0002_lamotteacceptablevalues"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaeAcceptableValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_value", models.FloatField()),
                ("upper_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.chemicalproperty",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "TAE Acceptable Value",
                "verbose_name_plural": "TAE Acceptable Values",
            },
        ),
    ]
