# Generated by Django 5.0.6 on 2025-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0009_crop_analysis_type"),
        ("soil_analysis", "0004_conversionfactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionfactor",
            name="nutrient",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="conversionfactor",
            unique_together={("crop", "chemical_property", "nutrient")},
        ),
    ]
