# Generated by Django 5.0.6 on 2025-02-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0009_crop_analysis_type"),
        ("soil_analysis", "0005_alter_conversionfactor_nutrient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseSaturationHighTecValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_value", models.FloatField()),
                ("upper_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.chemicalproperty",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Saturation High TEC Value",
                "verbose_name_plural": "Base Saturation High TEC Values",
                "unique_together": {("crop", "chemical_property")},
            },
        ),
    ]
